version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sleepr

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
    stdin_open: true
    tty: true
