version: '3.9'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: sh -c "pnpm i && pnpm start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
