version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=sleepr
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
